apiVersion: v1
entries:
  jaeger-all-in-one:
  - apiVersion: v2
    appVersion: 1.22.0
    created: "2021-04-16T12:44:51.3167001+02:00"
    description: Jaeger all-in-one helm chart for Kubernetes
    digest: e336b32e3da961d3850974ea0275a42cb9544eef75cd85910b3eb9fa52412a38
    home: https://github.com/hansehe/jaeger-all-in-one
    icon: https://raw.githubusercontent.com/hansehe/jaeger-all-in-one/master/helm/jaeger.png
    keywords:
    - jaeger
    - jaeger-all-in-one
    maintainers:
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: jaeger-all-in-one
    sources:
    - https://github.com/hansehe/jaeger-all-in-one
    type: application
    urls:
    - jaeger-all-in-one-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: 1.22.0
    created: "2021-04-16T12:44:51.3157172+02:00"
    description: Jaeger all-in-one helm chart for Kubernetes
    digest: 80e6e273228bc6eada30e0b0db7c60b34fcce9ebfadc20d76daf3d54f4112ea7
    home: https://github.com/hansehe/jaeger-all-in-one
    icon: https://raw.githubusercontent.com/hansehe/jaeger-all-in-one/master/helm/jaeger.png
    keywords:
    - jaeger
    - jaeger-all-in-one
    maintainers:
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: jaeger-all-in-one
    sources:
    - https://github.com/hansehe/jaeger-all-in-one
    type: application
    urls:
    - jaeger-all-in-one-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 1.22.0
    created: "2021-04-16T12:44:51.3107001+02:00"
    description: Jaeger all-in-one helm chart for Kubernetes
    digest: d768d031e3ffbf0353894a86a7863209cb1dbd386a01e83315ef58b5fe7a1583
    home: https://github.com/hansehe/jaeger-all-in-one
    icon: https://raw.githubusercontent.com/hansehe/jaeger-all-in-one/master/helm/jaeger.png
    keywords:
    - jaeger
    - jaeger-all-in-one
    maintainers:
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: jaeger-all-in-one
    sources:
    - https://github.com/hansehe/jaeger-all-in-one
    type: application
    urls:
    - jaeger-all-in-one-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 1.21.0
    created: "2021-04-16T12:44:51.3047026+02:00"
    description: Jaeger all-in-one helm chart for Kubernetes
    digest: 80c3ea39410998f562ce6ae1fb9e71a8ade7dc8b9b9b0f9a5cfbbd2d72c727bb
    home: https://github.com/hansehe/jaeger-all-in-one
    icon: https://raw.githubusercontent.com/hansehe/jaeger-all-in-one/master/helm/jaeger.png
    keywords:
    - jaeger
    - jaeger-all-in-one
    maintainers:
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: jaeger-all-in-one
    sources:
    - https://github.com/hansehe/jaeger-all-in-one
    type: application
    urls:
    - jaeger-all-in-one-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 1.21.0
    created: "2021-04-16T12:44:51.2996996+02:00"
    description: Jaeger all-in-one helm chart for Kubernetes
    digest: 68985c4defdb1808c3fdf2093c7dc4c062868f79fbf8cde8c3da917fecdf44d1
    home: https://github.com/hansehe/jaeger-all-in-one
    icon: https://raw.githubusercontent.com/hansehe/jaeger-all-in-one/master/helm/jaeger.png
    keywords:
    - jaeger
    - jaeger-all-in-one
    maintainers:
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: jaeger-all-in-one
    sources:
    - https://github.com/hansehe/jaeger-all-in-one
    type: application
    urls:
    - jaeger-all-in-one-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 1.21.0
    created: "2021-04-16T12:44:51.2937+02:00"
    description: Jaeger all-in-one helm chart for Kubernetes
    digest: ab7b3e8d18cf833825845d39681d89047496e5f88a37ad699e17a46efbb48e4b
    home: https://github.com/hansehe/jaeger-all-in-one
    icon: https://raw.githubusercontent.com/hansehe/jaeger-all-in-one/master/helm/jaeger.png
    keywords:
    - jaeger
    - jaeger-all-in-one
    maintainers:
    - email: hans.erik.heggem@gmail.com
      name: hansehe
    name: jaeger-all-in-one
    sources:
    - https://github.com/hansehe/jaeger-all-in-one
    type: application
    urls:
    - jaeger-all-in-one-0.1.0.tgz
    version: 0.1.0
generated: "2021-04-16T12:44:51.2877002+02:00"
